name: Deploy

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types: [completed]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    if: github.event.workflow_run.head_branch == 'master' && github.event.workflow_run.conclusion == 'success'
    name: Deploy to staging
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Deploy with Heroku
        run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/fierce-brook-31899.git HEAD:master -f
